### ISSUE TITLE
添加主题支持

### ISSUE THREAD

**Issue by WHG555** [ai-chen2050/obsidian-wechat-public-platform#1]
可以增加一些好看的主题，可以自已选择。或者自己修改主题。

**Comment by ai-chen2050** [comment]
等插件上官方市场后，个人时间空了，应该会考虑。感谢提议

**Comment by jianhekang** [comment]
插件很好用，感谢作者无私分享。
能增加主题选择会更好。

**Comment by ai-chen2050** [comment]
> 插件很好用，感谢作者无私分享。 能增加主题选择会更好。

很高兴能帮到你，欢迎 star 激励一下, 后面会考虑。

**Comment by jianhekang** [comment]
> > 插件很好用，感谢作者无私分享。 能增加主题选择会更好。
> 
> 很高兴能帮到你，欢迎 star 激励一下, 后面会考虑。

已加星，感谢您的无私分享。

**Comment by ai-chen2050** [comment]
- 新增 custom.css 配置文件，参见 Release [1.0.2](https://github.com/ai-chen2050/obsidian-wechat-public-platform/releases/tag/1.0.2)
