### ISSUE TITLE
如何定义文章属性字段

### ISSUE THREAD

**Issue by dengfei2013** [ai-chen2050/obsidian-wechat-public-platform#11]
您好，我在md文件前面，按照说明文档：

---
author: Blake   // for article author
thumb_media_id: "awM_2hMypzpKEBfvr0B09MPmBahsXrBzBhNAzIPXHzRYGjzErk7ZBs4L8nL7VpEY" // media id in wechat platform
banner: "https://images.unsplash.com/photo-1620266757065-5814239881fd?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=2400"
banner_path: "twitter.jpg"  // image file path
open_comment: 0
source_url: ""  // ref article url source
digest: ""
---

但是提交公众号草稿时，还是让选择封皮。而且作者也没有显示。

百家号提交时，显示：

Please set banner of article, banner, banner_path in file frontManager。

您看我应该如何修改，十分感谢。

**Comment by ai-chen2050** [comment]
本插件基本功能已经开发完成，并且是免费开源插件，且功能已经过测试。考虑到本人时间有限，若本插件对您有帮助，欢迎插件设置页适当赞赏打赏点红包，以激励开发者付费咨询。也可多自行多探索一下，都是可以的。若打赏付费咨询，可回复相应的微信支付用户名作为反馈。祝您生活愉快，希望能帮到您。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月19日(周四) 中午1:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ai-chen2050/obsidian-wechat-public-platform] 如何定义文章属性字段 (Issue #11)




 
您好，我在md文件前面，按照说明文档：
 
 
author: Blake   // for article author
 thumb_media_id: "awM_2hMypzpKEBfvr0B09MPmBahsXrBzBhNAzIPXHzRYGjzErk7ZBs4L8nL7VpEY" // media id in wechat platform
 banner: "https://images.unsplash.com/photo-1620266757065-5814239881fd?ixlib=rb-4.0.3&amp;q=85&amp;fm=jpg&amp;crop=entropy&amp;cs=srgb&amp;w=2400"
 banner_path: "twitter.jpg"  // image file path
 open_comment: 0
 source_url: ""  // ref article url source
 digest: ""
 
但是提交公众号草稿时，还是让选择封皮。而且作者也没有显示。
 
百家号提交时，显示：
 
Please set banner of article, banner, banner_path in file frontManager。
 
您看我应该如何修改，十分感谢。
