### ISSUE TITLE
[Feature]增加对当前MD文档的附件相对目录支持

### ISSUE THREAD

**Issue by sjhsbhqf** [ai-chen2050/obsidian-wechat-public-platform#2]
# 目前的问题

因为现在这个插件上传图片的时候，相对路径是相对于整个知识库，

但是很多人包括我保存图片附件的方式是 md文档和同名.assets图片附件文件夹放在一起保存。

很多人的喜好就是让一个文档的附件在一个目录里，不同文档的附件分开在不同文件夹。

这样图片在上传的时候，就会警告Please input correct file relative path inobsidian。
![b9a762b68686510f7b9c5ccab36bef7](https://github.com/ai-chen2050/obsidian-wechat-public-platform/assets/41407099/2739c262-2945-44cf-93e0-78d226a13441)

# 可能的解决方案

加一个设置，是相对于vault路径还是当前文档路径。

**Comment by ai-chen2050** [comment]
1

https://docs.obsidian.md/Reference/TypeScript+API/MetadataCache/getFirstLinkpathDest

**Comment by ai-chen2050** [comment]
请参考最新发行版本 [0.30.0](https://github.com/ai-chen2050/obsidian-wechat-public-platform/releases/tag/0.30.0)
