### ISSUE TITLE
建议将主题风格CSS分离

### ISSUE THREAD

**Issue by chengdefei** [ai-chen2050/obsidian-wechat-public-platform#4]
UP主,你的构思非常棒,果断给星了.

有两点建议

插件设置
增加一个主题选择的下拉列表

代码方面:
建议将主题风格CSS从main.js分离
可以新建一个文件夹"theme"
然后在这个文件夹下放入 主题风格的css
如此, 主题方便管理, 也方便用户自定义

主题风格的设置可以参考如下开源库, 它有33个主题:
https://github.com/sunbooshi/note-to-mp/

**Comment by ai-chen2050** [comment]
- 新增 custom.css 配置文件，参见 Release [1.0.2](https://github.com/ai-chen2050/obsidian-wechat-public-platform/releases/tag/1.0.2)
