### ISSUE TITLE
OB笔记的格式没有被完整上传

### ISSUE THREAD

**Issue by jianhekang** [ai-chen2050/obsidian-wechat-public-platform#5]
您好，
插件使用起来非常方便，有个小缺憾：OB笔记的内容上传到公众号草稿箱后，OB的格式没有完整同步上去，在公众号编辑器中变成了另外一个不太好看的格式。不知道是不是我哪里设置不对。

**Comment by ai-chen2050** [comment]
- 新增 custom.css 配置文件，参见 Release [1.0.2](https://github.com/ai-chen2050/obsidian-wechat-public-platform/releases/tag/1.0.2)
