### ISSUE TITLE
代码实现上有没有可能把当前应用的样式进行上传

### ISSUE THREAD

**Issue by chenbihao** [ai-chen2050/obsidian-wechat-public-platform#6]
代码实现上有没有可能把当前应用的样式进行上传，

例如我用了某个主题A，然后自己改了些CSS片段，可以作为整体发布成文章吗

**Comment by ai-chen2050** [comment]
- 新增 custom.css 配置文件，参见 Release [1.0.2](https://github.com/ai-chen2050/obsidian-wechat-public-platform/releases/tag/1.0.2)
