### ISSUE TITLE
可否添加一个选项：是否忽略一级标题

### ISSUE THREAD

**Issue by chenbihao** [ai-chen2050/obsidian-wechat-public-platform#7]
当文件标题跟一级标题重复的时候，上传上去会导致有H1大标题在正文中，希望能有个选项可以关闭

**Comment by ai-chen2050** [comment]
- 新增 custom.css 配置文件，参见 Release [1.0.2](https://github.com/ai-chen2050/obsidian-wechat-public-platform/releases/tag/1.0.2)
